baseURL = "https://tharuniyer.me"
title = "Tharun's blog"
theme = "PaperMod"
paginate = 5

# Enable features
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
defaultTheme = "light"  # Options: light, dark, auto
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true

[params.homeInfoParams]
Title = "Hi ðŸ‘‹ I'm Tharun"
Content = """
This website is my attempt at committing to writing in 2025. At work, I truly have no idea what I am or do. In my free time, I am trying to stay fit, perform magic and mentalism, and play the guitar.
"""

# Main menu
[[menu.main]]
name = "Posts"
url = "posts/"
weight = 1

[[menu.main]]
name = "Archives"
url = "archives"
weight = 2

[[menu.main]]
name = "Search"
url = "search/"
weight = 3

[[params.socialIcons]]
name = "linkedin"
url = "https://in.linkedin.com/in/tharun-iyer-70b804220"

[[params.socialIcons]]
name = "x"  # This is for Twitter/X
url = "https://x.com/TharunIyer"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]
